// Reference data only: every rendered car remains an original fictional design.
// Published metrics are kept separate from the calibrated game model.
export const realCarSpecs={
 black:{analogue:'McLaren 720S Coupe',referenceYear:'2017–2023',powerKw:529.5,powerLabel:'720 PS / 710 bhp',torqueNm:770,mass:1419,massBasis:'DIN kerb, no driver',drivetrain:'RWD',gears:7,transmission:'7-speed dual clutch',topMph:212,acceleration:{mph:62.137119,time:2.9,label:'0–100 km/h: 2.9 s (manufacturer specification table)'},secondaryAcceleration:{mph:124.274238,time:7.8},braking:{mph:62.137119,meters:30,label:'100–0 km/h: 30 m, manufacturer'},notes:'The page introduction says 2.8 s; the detailed specification table says 2.9 s. This model uses the table.',sources:[{title:'McLaren 720S technical specifications',url:'https://cars.mclaren.com/en/super-series/720s'}]},
 silver:{analogue:'Aston Martin DB12 Coupe',referenceYear:'2023 base V8',powerKw:500.1,powerLabel:'680 PS',torqueNm:800,mass:1788,massBasis:'EU kerb with lightweight options, as published',drivetrain:'RWD',gears:8,transmission:'8-speed automatic',topMph:202,acceleration:{mph:62.137119,time:3.6,label:'0–100 km/h: 3.6 s, manufacturer'},braking:{mph:60,meters:33,label:'60–0 mph: 33 m, simulation estimate'},notes:'Base DB12, not the later DB12 S. Published mass includes lightweight options. Stopping distance is an authored dry-road estimate.',sources:[{title:'Aston Martin DB12 specifications',url:'https://www.astonmartin.com/en/models/db12'}]},
 red:{analogue:'Koenigsegg Jesko Attack',referenceYear:'2024 technical specification',powerKw:955,powerLabel:'1280 bhp gasoline / 1600 bhp E85',torqueNm:1500,mass:1420,massBasis:'Curb weight, manufacturer technical specification',publishedDryMass:1320,drivetrain:'RWD',gears:9,transmission:'9-speed Light Speed Transmission (LST)',topMph:null,acceleration:{mph:62.137119,time:null,label:'Manufacturer does not publish a 0–100 km/h time'},secondaryAcceleration:{mph:124.274238,time:null},braking:{mph:62.137119,meters:30,label:'Simulation estimate; manufacturer specifies 410 mm front / 395 mm rear carbon-ceramic brakes'},notes:'The Jesko Attack produces 1280 bhp on gasoline and 1600 bhp on E85, with 1500 Nm maximum torque and a 9-speed LST. Koenigsegg has not published a certified top-speed or standing-start acceleration figure for the Attack; the game cap and acceleration are labeled separately as arcade tuning.',sources:[{title:'Koenigsegg Jesko Attack technical specifications',url:'https://www.koenigsegg.com/technical-specifications-jesko-attack'},{title:'Koenigsegg Jesko Attack model page',url:'https://www.koenigsegg.com/model/jesko-attack'}]},
 rally:{analogue:'Toyota GR Yaris 6MT',referenceYear:'2020 launch specification',powerKw:192,powerLabel:'261 DIN hp / 257 bhp',torqueNm:360,mass:1280,massBasis:'Kerb without driver',drivetrain:'AWD',gears:6,transmission:'6-speed manual, automated in game',topMph:143,acceleration:{mph:62.137119,time:5.5,label:'0–100 km/h: under 5.5 s, manufacturer; model target 5.5 s'},braking:{mph:60,meters:34,label:'60–0 mph: 34 m, simulation estimate'},notes:'Uses the original 261 DIN hp model, not the later 280 hp car. Manual shifts are automated. Braking distance is estimated.',sources:[{title:'Toyota GR Yaris launch technical specifications',url:'https://media.toyota.co.uk/the-new-toyota-gr-yaris-forged-in-the-heat-of-world-rally-competition/'}]},
 muscle:{analogue:'Ford Mustang GT Fastback 10AT',referenceYear:'2024 European specification',powerKw:328,powerLabel:'446 PS / 328 kW',torqueNm:540,mass:1836,massBasis:'Simulation kerb estimate; equipment and markets vary',drivetrain:'RWD',gears:10,transmission:'10-speed automatic',topMph:155,acceleration:{mph:62.137119,time:4.9,label:'0–100 km/h: 4.9 s, Ford UK automatic specification'},braking:{mph:60,meters:36,label:'60–0 mph: 36 m, simulation estimate'},notes:'European 446 PS GT, not the US 480 hp car or Dark Horse. 1836 kg is an estimate based on Ford published GT automatic mass in another market. Stopping distance is estimated.',sources:[{title:'Ford European Mustang launch power and torque',url:'https://media.ford.com/content/fordmedia/feu/gb/en/news/2024/02/01/new-ford-mustang-is-an-icon-reborn-.html'},{title:'Ford UK 2024 Mustang drivetrain and performance',url:'https://www.ford.co.uk/support/how-tos/support-search-only/vehicle-index/ford-mustang-2024'},{title:'Ford GT automatic mass, Brazilian specification',url:'https://www.ford.com.br/content/dam/Ford/website-assets/latam/br/nameplate/2024/mustang/pdf/fbr-mustang-gt-performance-ficha-tecnica.pdf'}]},
 roadster:{analogue:'Mazda MX-5 2.0 Roadster 6MT',referenceYear:'2025 UK 184 PS soft top',powerKw:135.3,powerLabel:'184 PS',torqueNm:205,mass:1053,massBasis:'1128 kg maximum including 75 kg driver, minus driver',drivetrain:'RWD',gears:6,transmission:'6-speed manual, automated in game',topMph:136,acceleration:{mph:62.137119,time:6.5,label:'0–100 km/h: 6.5 s, manufacturer'},braking:{mph:60,meters:35,label:'60–0 mph: 35 m, simulation estimate'},notes:'Soft-top 2.0 model, not the RF. Brochure mass includes a 75 kg driver; simulation removes that driver for consistency with most entries. Braking distance is estimated.',sources:[{title:'Mazda UK September 2025 MX-5 specifications, page 22',url:'https://media-assets.mazda.eu/raw/upload/mazdauk/globalassets/uk/pdfs/fy160/p2.5/mx-5/mazda-mx-5-ps-guide-sept-25.pdf?rnd=4a45a8'}]},
 electric:{analogue:'Tesla Model S Plaid (200 mph hardware)',referenceYear:'Current published specification',powerKw:760.6,powerLabel:'1020 hp peak',torqueNm:null,mass:4802*.45359237,massBasis:'4802 lb manufacturer curb mass converted to kg',drivetrain:'Tri-motor AWD',gears:1,transmission:'Single-speed reduction',topMph:200,acceleration:{mph:60,time:2.28,label:'1.99 s manufacturer with rollout; 2.28 s standing-start model target'},publishedZero60:1.99,braking:{mph:60,meters:33.5,label:'60–0 mph: 33.5 m, simulation estimate'},notes:'200 mph requires the manufacturer hardware upgrade; standard limit is 163 mph. Peak combined torque is not published in the cited source. Standing-start target follows MotorTrend 2022 original testing; current mass is not the tested car mass. No fake gear changes.',sources:[{title:'Tesla Model S specifications and performance footnotes',url:'https://www.tesla.com/models?source=homepage'},{title:'MotorTrend instrumented standing-start Plaid test',url:'https://www.motortrend.com/reviews/2022-tesla-model-s-plaid-first-test-review'}]},
 safari:{analogue:'Land Rover Defender 110 P400',referenceYear:'2025 five-seat, standard wheels',powerKw:294,powerLabel:'400 PS / 294 kW',torqueNm:550,mass:2326,massBasis:'DIN unladen, five seats, no driver',drivetrain:'AWD',gears:8,transmission:'8-speed automatic',topMph:119,acceleration:{mph:60,time:5.8,label:'0–60 mph: 5.8 s; 0–100 km/h: 6.1 s, manufacturer'},braking:{mph:60,meters:42,label:'60–0 mph: 42 m, simulation estimate'},notes:'119 mph standard-wheel configuration; manufacturer allows 130 mph with 22-inch wheels. Braking distance is an authored estimate. Transmission shifts are simplified.',sources:[{title:'Land Rover Defender 2025 technical data, pages 15–16',url:'https://www.landrover.com/defender-wltp/'},{title:'Land Rover Defender 110 transmission data',url:'https://jlrnewsroom.media/wp-content/uploads/2020/09/Land-Rover-Defender-110_TECH-DATA_21MY_090920.pdf'}]}
};
export const referenceDate='2026-09-12';

