import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {anchorNearJunction,routeBlockFor} from './sceneryPolicy.js';
import {buildMammalFace,buildBirdFace,detailFeather,installWildlifeDetails,bodySurface,birdHeadFrame,birdSkull} from './wildlifeDetail8.js';

// All anatomy, markings, feather vanes, fur strokes and textures below are
// authored here. No downloaded model, image, recording or animation is used.
export const wildlifeCatalog={
 coastline:{ground:['Roe deer','Red fox','Harbor seal'],birds:['Herring gull','Common tern','Cormorant']},
 tundra:{ground:['Reindeer','Arctic fox','Arctic hare'],birds:['Snowy owl','Snow bunting','Ptarmigan']},
 desert:{ground:['Bighorn sheep','Coyote','Black-tailed jackrabbit'],birds:['Red-tailed hawk','Common raven','Mourning dove']},
 jungle:{ground:['Lowland tapir','Capybara','Jaguar'],birds:['Scarlet macaw','Keel-billed toucan','Little blue heron']}
};
const ground={
 'Roe deer':{kind:'deer',coat:0x936c42,belly:0xd5bea0,length:1.20,width:.29,height:.85,head:.26,neck:.60,ears:.22,tail:.12,scale:1.10},
 'Red fox':{kind:'fox',coat:0xb45a2d,belly:0xe6d8bb,length:1.00,width:.21,height:.43,head:.23,neck:.22,ears:.16,tail:.70,scale:1.04},
 'Harbor seal':{kind:'seal',coat:0x727c78,belly:0xbfc0b1,length:1.48,width:.46,height:.22,head:.28,neck:.10,ears:0,tail:.17,scale:1.06},
 'Reindeer':{kind:'reindeer',coat:0x69584a,belly:0xd0c6ad,length:1.44,width:.37,height:.98,head:.34,neck:.64,ears:.19,tail:.18,scale:1.20},
 'Arctic fox':{kind:'fox',coat:0xdce4e5,belly:0xf1eeDF,length:.95,width:.25,height:.40,head:.22,neck:.23,ears:.11,tail:.63,scale:1.03},
 'Arctic hare':{kind:'hare',coat:0xe4e7e1,belly:0xfcf5e5,length:.64,width:.24,height:.30,head:.22,neck:.17,ears:.36,tail:.12,scale:1.10},
 'Bighorn sheep':{kind:'bighorn',coat:0x977c62,belly:0xdbd2ba,length:1.23,width:.39,height:.80,head:.32,neck:.37,ears:.14,tail:.16,scale:1.15},
 'Coyote':{kind:'coyote',coat:0x887d64,belly:0xc6b999,length:1.19,width:.26,height:.62,head:.29,neck:.25,ears:.21,tail:.57,scale:1.02},
 'Black-tailed jackrabbit':{kind:'hare',coat:0x9c9074,belly:0xd6c9a6,length:.68,width:.24,height:.31,head:.22,neck:.15,ears:.49,tail:.16,scale:1.08},
 'Lowland tapir':{kind:'tapir',coat:0x625e55,belly:0x8b8373,length:1.65,width:.47,height:.65,head:.36,neck:.25,ears:.13,tail:.12,scale:1.13},
 'Capybara':{kind:'capybara',coat:0x887552,belly:0xb39c76,length:1.09,width:.34,height:.40,head:.31,neck:.10,ears:.07,tail:0,scale:1.09},
 'Jaguar':{kind:'cat',coat:0xbe923e,belly:0xe8ce91,length:1.45,width:.34,height:.59,head:.34,neck:.22,ears:.09,tail:.83,scale:1.15}
};
const bird={
 'Herring gull':{coat:0xd3dce0,back:0x81949c,tip:0x222a2d,beak:0xd9b237,size:1.06,wing:1.02,chord:.34,tail:.22,flap:2.7,neck:.10},
 'Common tern':{coat:0xe4e9e6,back:0x9aadb6,tip:0x323d43,beak:0xca552f,size:.76,wing:.94,chord:.22,tail:.43,flap:4.6,neck:.04,fork:true,cap:true},
 'Cormorant':{coat:0x273b38,back:0x344443,tip:0x172326,beak:0xaca770,size:1.15,wing:1.02,chord:.31,tail:.45,flap:3.2,neck:.32},
 'Snowy owl':{coat:0xe3e6dc,back:0xdbdfd4,tip:0x8b948c,beak:0x3b443f,size:1.12,wing:1.02,chord:.48,tail:.24,flap:2.0,neck:0,owl:true},
 'Snow bunting':{coat:0xe2e5dc,back:0x717c7c,tip:0x303a3c,beak:0xcdb783,size:.56,wing:.55,chord:.24,tail:.30,flap:7.7,neck:.03},
 'Ptarmigan':{coat:0xdde2db,back:0xc2cbc6,tip:0x4f5c58,beak:0x39423b,size:.88,wing:.66,chord:.41,tail:.19,flap:5.0,neck:.04},
 'Red-tailed hawk':{coat:0x9c7c55,back:0x6c5340,tip:0x3d3731,beak:0x8b8163,size:1.20,wing:1.15,chord:.43,tail:.42,flap:1.7,neck:.05,raptor:true},
 'Common raven':{coat:0x24313a,back:0x2e3d49,tip:0x151f27,beak:0x293239,size:1.03,wing:1.01,chord:.35,tail:.39,flap:2.6,neck:.10},
 'Mourning dove':{coat:0xb1a391,back:0x8f8175,tip:0x544e47,beak:0x655d54,size:.70,wing:.67,chord:.26,tail:.37,flap:6.1,neck:.09},
 'Scarlet macaw':{coat:0xc94230,back:0xcc4c33,tip:0x327a9f,beak:0xe1d4b1,size:1.1,wing:.94,chord:.40,tail:.85,flap:3.0,neck:.07,macaw:true},
 'Keel-billed toucan':{coat:0x273530,back:0x34473a,tip:0x1d2a2c,beak:0x9ac15a,size:.87,wing:.76,chord:.32,tail:.34,flap:4.2,neck:.04,toucan:true},
 'Little blue heron':{coat:0x60798a,back:0x576879,tip:0x3d5263,beak:0xa2a675,size:1.02,wing:1.02,chord:.34,tail:.20,flap:2.0,neck:.39,heron:true}
};
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
const up=new T.Vector3(0,1,0),black=0x1c231f,ivory=0xefe5ce;
function tinted(g,color,variation=0,mark){const p=g.attributes.position,c=new T.Color(color),out=[];for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),v=1+variation*(Math.sin(x*39+y*43+z*31)*.45+Math.sin(x*89-z*53)*.25),a=c.clone().multiplyScalar(v);if(mark)mark(a,x,y,z);out.push(a.r,a.g,a.b)}g.setAttribute('color',new T.Float32BufferAttribute(out,3));return g}
function add(parts,g,color,pos=[0,0,0],scale=[1,1,1],rotation=[0,0,0],mark){const m=new T.Matrix4().compose(new T.Vector3(...pos),new T.Quaternion().setFromEuler(new T.Euler(...rotation)),new T.Vector3(...scale));g.applyMatrix4(m);tinted(g,color,.022,mark);parts.push(g);}
function oval(parts,color,pos,scale,rotation=[0,0,0],mark){add(parts,new T.SphereGeometry(1,16,10),color,pos,scale,rotation,mark)}
function limb(parts,color,a,b,r1,r2){const A=new T.Vector3(...a),B=new T.Vector3(...b),m=new T.Matrix4().compose(A.clone().add(B).multiplyScalar(.5),new T.Quaternion().setFromUnitVectors(up,B.clone().sub(A).normalize()),new T.Vector3(1,1,1)),g=new T.CylinderGeometry(r2,r1,A.distanceTo(B),14,3);g.applyMatrix4(m);tinted(g,color,.05);parts.push(g)}
function tube(parts,color,points,radius,segments=14){const path=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));add(parts,new T.TubeGeometry(path,segments,radius,8,false),color)}
function joined(parts){const normalized=parts.map(p=>{if(!p.attributes.uv){const uv=[],a=p.attributes.position;for(let i=0;i<a.count;i++)uv.push(a.getX(i)+a.getZ(i)*.31,a.getY(i)+a.getZ(i)*.14);p.setAttribute('uv',new T.Float32BufferAttribute(uv,2));}return p.index?p.toNonIndexed():p}),g=mergeGeometries(normalized,false);new Set([...normalized,...parts]).forEach(p=>p.dispose());if(!g)throw new Error('Wildlife geometry merge failed');g.computeBoundingSphere();return g}
function sculptBody(c){const positions=[],index=[],rows=56,sides=40;for(let i=0;i<=rows;i++)for(let j=0;j<=sides;j++){const p=bodySurface(c,i/rows,j/sides*Math.PI*2);positions.push(p.x,p.y,p.z);}for(let i=0;i<rows;i++)for(let j=0;j<sides;j++){let a=i*(sides+1)+j,b=a+1;index.push(a,a+sides+1,b,b,a+sides+1,b+sides+1);}for(const end of[0,1]){const center=positions.length/3,ring=end*rows*(sides+1);positions.push(0,c.height,(end?.57:-.57)*c.length);for(let j=0;j<sides;j++)index.push(center,ring+j+(end?1:0),ring+j+(end?0:1));}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setIndex(index);g.computeVertexNormals();return g;}
function taperedNeck(parts,c,end){const path=new T.CatmullRomCurve3([new T.Vector3(0,c.height,-c.length*.24),new T.Vector3(0,c.height+c.neck*.50,-c.length*.39),new T.Vector3(...end)]),p=[],ids=[],rows=28,sides=24;for(let i=0;i<=rows;i++){const t=i/rows,at=path.getPoint(t),q=new T.Quaternion().setFromUnitVectors(up,path.getTangent(t)),r=T.MathUtils.lerp(c.width*.54,c.head*.28,t);for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2,v=new T.Vector3(Math.sin(a)*r,0,Math.cos(a)*r*1.14).applyQuaternion(q).add(at);p.push(v.x,v.y,v.z);}}for(let i=0;i<rows;i++)for(let j=0;j<sides;j++){let a=i*(sides+1)+j,b=a+sides+1;ids.push(a,a+1,b,a+1,b+1,b);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex(ids);g.computeVertexNormals();add(parts,g,c.coat);}

function markings(c){return(col,x,y,z)=>{if(y<c.height-.04)col.lerp(new T.Color(c.belly),Math.min(.72,(-y+c.height)*2.4));if(c.kind==='seal'){const spot=Math.sin(x*43+z*9)*Math.sin(z*35-y*14);if(spot>.48)col.multiplyScalar(.62);}}}
function furGeometry(c){const ps=[],cs=[],r=rng(Math.floor(c.length*9431+c.coat));if(c.kind==='seal')return null;const color=new T.Color(c.coat);for(let i=0;i<360;i++){const a=r()*Math.PI*2,p=bodySurface(c,.1+r()*.8,a),n=new T.Vector3(Math.sin(a),Math.cos(a),0),len=(c.kind==='fox'||c.kind==='reindeer'?.014:.006)*(1+r());ps.push(p.x-.001,p.y,p.z,p.x+.001,p.y,p.z,p.x+n.x*len*.16,p.y+n.y*len*.16-len*.2,p.z+len);const col=color.clone().multiplyScalar(.94+r()*.12);for(let k=0;k<3;k++)cs.push(col.r,col.g,col.b);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(ps,3));g.setAttribute('color',new T.Float32BufferAttribute(cs,3));g.computeVertexNormals();return g;}

export function buildWildlifeModel(name,{ultra=false}={}){
 const c=ground[name];if(!c)throw new Error(`Unknown wildlife species: ${name}`);const body=[],head=[],leg=[],tail=[];add(body,sculptBody(c),c.coat,[0,0,0],[1,1,1],[0,0,0],markings(c));
 const hz=-c.length*.49,headY=c.height+c.neck;taperedNeck(body,c,[0,headY-.025,hz+c.head*.20]);
 const face=buildMammalFace(c,name),detail=ultra?face:null;head.push(face.skin);if(!ultra){head.push(face.eyes);face.wet?.dispose();face.fur?.dispose();}

 if(c.kind==='deer'||c.kind==='reindeer')for(let side of[-1,1]){const a=side*c.head*.29,top=c.kind==='reindeer'?.72:.43;const stem=[[a,c.head*.40,c.head*.1],[a*1.7,.35,.08],[a*2,.53,.15],[a*2.4,top,.03]];tube(head,0x9c8970,stem,.021);for(let j=0;j<3;j++)limb(head,0xaa9475,[a*(1.5+j*.25),.34+j*.13,.08],[a*(2.7+j*.25),.47+j*.16,-.12],.018,.006);}
 if(c.kind==='bighorn')for(let side of[-1,1]){const points=[];for(let j=0;j<37;j++){const t=j/36,angle=t*Math.PI*1.70;points.push(new T.Vector3(side*(c.head*.38+t*.055),c.head*.37+Math.sin(angle)*.23,.06+Math.cos(angle)*.22));}const path=new T.CatmullRomCurve3(points),p=[],ix=[],rows=64,sides=20,frames=path.computeFrenetFrames(rows,false);for(let i=0;i<=rows;i++){const t=i/rows,at=path.getPoint(t),q=new T.Quaternion().setFromUnitVectors(up,path.getTangent(t)),radius=.058*Math.pow(1-t,.64)+.002;for(let j=0;j<=sides;j++){const angle=j/sides*Math.PI*2,flute=1+.018*Math.sin(t*240),v=frames.normals[i].clone().multiplyScalar(Math.sin(angle)*radius*flute).addScaledVector(frames.binormals[i],Math.cos(angle)*radius*.86*flute).add(at);p.push(v.x,v.y,v.z);}}for(let i=0;i<rows;i++)for(let j=0;j<sides;j++){const a=i*(sides+1)+j,b=a+sides+1;ix.push(a,a+1,b,a+1,b+1,b);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex(ix);g.computeVertexNormals();add(head,g,0x88745a);}
 if(c.kind==='seal'){for(let side of[-1,1]){oval(body,c.coat,[side*.41,.13,-.22],[.11,.035,.40],[0,side*.67,.14]);oval(tail,c.coat,[side*.14,-.035,.10],[.15,.045,.30],[0,side*.32,0]);}}
 else {const len=c.height-.12,positions=[],indices=[],rows=30,sides=18;for(let i=0;i<=rows;i++){const t=i/rows,y=-t*(len+.015),z=.045*Math.sin(t*Math.PI),radius=c.width*(.24*(1-t)**1.5+.083*t);for(let j=0;j<=sides;j++){const angle=j/sides*Math.PI*2;positions.push(Math.sin(angle)*radius,y,z+Math.cos(angle)*radius*.9);}}for(let i=0;i<rows;i++)for(let j=0;j<sides;j++){const a=i*(sides+1)+j,b=a+sides+1;indices.push(a,b,a+1,a+1,b,b+1);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();add(leg,g,c.coat,[0,0,0],[1,1,1],[0,0,0],(color,x,y)=>{if(c.kind==='fox'&&y<-len*.5)color.lerp(new T.Color(0x4d392e),.75);});oval(leg,['deer','reindeer','bighorn'].includes(c.kind)?0x3b3830:c.coat,[0,-len-.025,-.047],[c.width*.15,.038,c.kind==='hare'?.135:.080]);if(c.tail){const curve=c.kind==='cat'?[[0,0,0],[.04,-.02,c.tail*.4],[.11,.02,c.tail*.8],[.20,.15,c.tail]]:[[0,0,0],[0,-.04,c.tail*.45],[.05,-.19,c.tail]];tube(tail,c.coat,curve,c.kind==='fox'?.10:c.kind==='coyote'?.075:.033);if(c.kind==='fox')oval(tail,c.belly,[.05,-.18,c.tail*.94],[.073,.075,.14],[.35,0,0]);if(c.kind==='hare')oval(tail,c.belly,[0,0,.07],[.08,.09,.10]);}}
 return {name,config:c,detail,parts:{body:joined(body),head:joined(head),leg:leg.length?joined(leg):null,tail:tail.length?joined(tail):null,fur:furGeometry(c)},headPivot:[0,headY,hz],tailPivot:[0,c.height,c.length*.50]};
}
function feather(parts,color,start,length,width,angle=0,lift=0){const ps=[],ix=[];for(let i=0;i<=8;i++){let t=i/8,x=start[0]+t*length,y=start[1]+Math.sin(t*Math.PI)*lift,z=start[2]+t*angle,w=Math.sin(Math.PI*Math.pow(t,.6))*width*.5;ps.push(x,y,z-w,x,y+.008,z+w)}for(let i=0;i<8;i++){let k=i*2;ix.push(k,k+1,k+2,k+1,k+3,k+2)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(ps,3));g.setIndex(ix);g.computeVertexNormals();add(parts,g,color);}
function mirrorGeometry(geo){const mirrored=geo.clone().scale(-1,1,1);for(const a of Object.values(mirrored.attributes)){for(let i=0;i<a.count;i+=3)for(let k=0;k<a.itemSize;k++){const j=(i+1)*a.itemSize+k,l=(i+2)*a.itemSize+k,t=a.array[j];a.array[j]=a.array[l];a.array[l]=t;}a.needsUpdate=true;}mirrored.computeVertexNormals();return mirrored;}
export function buildBirdModel(name,{ultra=false}={}){
 const c=bird[name];if(!c)throw new Error('Unknown bird species: '+name);const body=[],wing=[],makeFeather=ultra?detailFeather:feather,face=buildBirdFace(c,name),detail=ultra?face:null,f=birdHeadFrame(c);
 // A continuous keel and tapered rump, with the neck seated inside both forms.
 const p=[],ix=[],rows=32,sides=32,profile=[[-.265,.028,.040],[-.19,.078,.092],[-.075,.101,.116],[.065,.090,.099],[.18,.064,.062],[.275,.016,.024]];
 const path=new T.CatmullRomCurve3(profile.map(x=>new T.Vector3(...x)));for(let i=0;i<=rows;i++){const q=path.getPoint(i/rows);for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2;p.push(Math.sin(a)*q.y,Math.cos(a)*q.z,q.x);}}for(let i=0;i<rows;i++)for(let j=0;j<sides;j++){const a=i*(sides+1)+j,b=a+sides+1;ix.push(a,b,a+1,a+1,b,b+1);}for(const end of[0,1]){const center=p.length/3,ring=end*rows*(sides+1);p.push(0,0,end?.275:-.265);for(let j=0;j<sides;j++)ix.push(center,ring+j+(end?1:0),ring+j+(end?0:1));}const torso=new T.BufferGeometry();torso.setAttribute('position',new T.Float32BufferAttribute(p,3));torso.setIndex(ix);torso.computeVertexNormals();add(body,torso,c.coat,[0,0,0],[1,1,1],[0,0,0],(col,x,y,z)=>{if(y>.02)col.lerp(new T.Color(c.back),.78);if(c.toucan&&z<-.15)col.set(0xd8b840);});
 tube(body,c.coat,c.heron?[[0,.024,-.18],[0,.065,-.255],[0,.014,-.335],[0,.065,f.hz+.035]]:[[0,.024,-.18],[0,.063,-.26],[0,f.y-.010,f.hz+.050]],c.owl?.067:c.macaw?.047:.036,18);birdSkull(body,c);body.push(face.skin);if(!ultra){body.push(face.eyes);face.wet?.dispose();}
 for(let i=0;i<9;i++){const v=(i-4)/4,len=c.tail*(c.fork?.62+Math.abs(v)*.55:1-Math.abs(v)*.20),q=[];makeFeather(q,c.raptor?0xa85936:c.macaw?0xaf3b2b:c.back,[0,0,0],len,.057,0,.004);add(body,joined(q),c.raptor?0xa85936:c.macaw?0xb5402f:c.back,[v*.040,-.020,.20],[1,1,1],[0,-Math.PI/2-v*.13,0]);}
 function vane(color,start,end,width,lift=.007){const dx=end[0]-start[0],dz=end[2]-start[2],len=Math.hypot(dx,dz),q=[];makeFeather(q,color,[0,0,0],len,width,0,lift);add(wing,joined(q),color,start,[1,1,1],[0,-Math.atan2(dz,dx),0]);}
 const outline=[[0,-.14],[.35,-.30],[.65,-.36],[.96,-.22],[.99,-.10],[.84,.53],[.58,.70],[.18,.67],[0,.33]],shape=new T.Shape(outline.map(([x,z])=>new T.Vector2(x*c.wing,-z*c.chord))),core=new T.ShapeGeometry(shape,20);core.rotateX(-Math.PI/2);core.translate(0,-.004,0);add(wing,core,c.back,[0,0,0],[1,1,1],[0,0,0],(col,x)=>{if(c.macaw)col.set(x<c.wing*.45?c.coat:x<c.wing*.66?0xc5a137:0x286c8b);});
 // Secondaries trail the forearm; primaries fan from the wrist into a tapered tip.
 for(let i=0;i<10;i++){const t=i/9,x=c.wing*(.04+t*.56),front=-c.chord*(.14+.19*t),back=c.chord*(.76-.12*t);vane(c.macaw?(i<4?0xcb4934:0xc3a537):c.back,[x,0,front],[x+c.wing*.10,0,back],c.wing*.105);}
 for(let i=0;i<9;i++){const t=i/8;vane(c.macaw?0x286c8b:c.tip,[c.wing*(.56+.10*t),.005,-c.chord*(.27+.07*t)],[c.wing*(.70+.30*Math.sin((.18+t*.82)*Math.PI*.62)),0,c.chord*(.72-.94*t)],c.chord*(.22-.055*t));}
 for(let i=0;i<14;i++){const t=i/13,x=t*c.wing*.67;vane(c.macaw?(t>.54?0xc5a137:c.coat):c.coat,[x,.010,-c.chord*(.14+.20*t)],[x+c.wing*.08,.01,c.chord*(.16-.16*t)],c.wing*.078,.003);}
 for(let side of[-1,1]){limb(body,c.heron?0x829181:0x8e7c64,[side*.040,-.073,.09],[side*.040,-.10,c.heron?.58:.20],.007,.005);for(let j=0;j<3;j++)limb(body,0x746b50,[side*.040,-.10,c.heron?.58:.20],[side*.040+(j-1)*.015,-.11,c.heron?.64:.23],.003,.0015);}
 const rightWing=joined(wing);return {name,config:c,detail,body:joined(body),wing:rightWing,leftWing:mirrorGeometry(rightWing)};
}

function coatTexture(){const size=256,data=new Uint8Array(size*size*4),r=rng(94381);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=(y*size+x)*4,strand=Math.sin(x*1.23+Math.sin(y*.093)*1.6),pores=Math.sin(x*.29+y*.41)*Math.sin(y*.67-x*.34),v=195+strand*26+pores*9+r()*12;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255}const t=new T.DataTexture(data,size,size);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(2,1);t.generateMipmaps=true;t.minFilter=T.LinearMipmapLinearFilter;t.anisotropy=8;t.needsUpdate=true;return t}
function rosetteTexture(){const size=512,data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const u=x/size*14,v=y/size*14,ix=Math.floor(u),iy=Math.floor(v),phase=Math.sin(ix*31.27+iy*47.91),dx=(u-ix-.5-phase*.14)*(1+phase*.18),dy=(v-iy-.5-Math.sin(ix*17.13+iy*23.1)*.14),a=Math.atan2(dy,dx),d=Math.hypot(dx,dy)*(1+Math.sin(a*4+phase*4)*.11),r=.245+phase*.055,ring=Math.max(0,1-Math.abs(d-r)/.053),center=Math.max(0,1-d/.095)*(phase>.3?.65:0),breakup=.78+.22*Math.sin(a*3.0+ix),s=Math.max(ring*breakup,center),n=(Math.sin(x*1.3+y*.43)+Math.sin(x*.31-y*.93))*2,i=(y*size+x)*4;data[i]=Math.min(255,255-s*212+n);data[i+1]=Math.min(255,255-s*221+n);data[i+2]=Math.min(255,255-s*226+n);data[i+3]=255;}const tex=new T.DataTexture(data,size,size);tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=8;tex.generateMipmaps=true;tex.minFilter=T.LinearMipmapLinearFilter;tex.magFilter=T.LinearFilter;tex.needsUpdate=true;return tex}
export function createWildlifeMaterial(name){const coat=coatTexture();return new T.MeshStandardMaterial({vertexColors:true,roughness:ground[name]?.kind==='seal'?.80:1,roughnessMap:coat,bumpMap:coat,bumpScale:ground[name]?.kind==='seal'?.0006:.0008,map:ground[name]?.kind==='cat'?rosetteTexture():null});}
function shadowTexture(){const n=64,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const d=((x-31.5)/32)**2+((y-31.5)/32)**2,k=(y*n+x)*4,a=Math.max(0,1-d)**2*135;data[k]=data[k+1]=data[k+2]=255;data[k+3]=a}const t=new T.DataTexture(data,n,n);t.needsUpdate=true;return t}
export function installWildlifeArt(world,biome){
 const cat=wildlifeCatalog[biome];if(!cat)throw new Error(`Unknown wildlife biome: ${biome}`);
 const root=new T.Group();root.name=`Authored ${biome} wildlife`;world.scene.add(root);world.wildlifeArtRoot=root;
 const air=new T.Group();air.name=`Authored ${biome} birds`;world.scene.add(air);
 const feathers=new T.MeshStandardMaterial({vertexColors:true,roughness:.83,side:T.DoubleSide}),hair=new T.MeshStandardMaterial({vertexColors:true,roughness:1,side:T.DoubleSide});
 const models=cat.ground.map(buildWildlifeModel),birdModels=cat.birds.map(buildBirdModel),groundSets=[],birdSets=[],r=rng(638192),dummy=new T.Object3D(),matrix=new T.Matrix4(),parentMatrix=new T.Matrix4(),localMatrix=new T.Matrix4();let quality='High',lastTime=0,renderedAnimals=0,renderedBirds=0,visibleSpecies=[],renderedHazards=[];
 const shadow=new T.InstancedMesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({map:shadowTexture(),color:0x182321,transparent:true,opacity:.60,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}),60);shadow.name='Wildlife ground contact shading';shadow.frustumCulled=false;root.add(shadow);
 const cast=(g,mat,count,parent)=>{const m=new T.InstancedMesh(g,mat,count);m.castShadow=true;m.receiveShadow=true;m.frustumCulled=false;m.instanceMatrix.setUsage(T.DynamicDrawUsage);parent.add(m);return m};
 for(let si=0;si<models.length;si++){const model=models[si],parts={},coat=createWildlifeMaterial(model.name);for(const [name,g]of Object.entries(model.parts))if(g){parts[name]=cast(g,name==='fur'?hair:coat,name==='leg'?80:20,root);parts[name].name=`${model.name} ${name}`;}const individuals=[];for(let ti=0;ti<5;ti++)for(let j=0;j<4;j++){let side=biome==='coastline'&&model.config.kind==='seal'?-1:((si+j+ti)%3===0?-1:1),x=side*(17.4+si*.8+j*1.42),z=-13-j*37-si*6;if(biome==='coastline'&&model.config.kind==='seal')x=-28.0-j*.40;const tile=world.tiles[ti],sample=(x,z)=>tile.userData.terrainHeight?.(x,z)??(x<0?(x>-23?-.1:Math.max(-3.25,-.1-(-x-23)*.18)):-.12);individuals.push({ti,j,x,z,y:sample(x,z),sample,phase:r()*6.28,heading:side<0?-1.1:1.0,scale:model.config.scale*(.86+r()*.23)});}groundSets.push({model,parts,individuals});}
 for(let si=0;si<birdModels.length;si++){const model=birdModels[si],body=cast(model.body,feathers,16,air),wings=cast(model.wing,feathers,16,air),leftWings=cast(model.leftWing,feathers,16,air);body.name=`${model.name} feathered body`;wings.name=`${model.name} right primary wings`;leftWings.name=`${model.name} left primary wings`;const individuals=Array.from({length:16},(_,i)=>({phase:r()*6.28,x:(i%2?-1:1)*(20+r()*45),y:7+si*4+r()*9,z:-15-r()*240,scale:model.config.size*(.86+r()*.3),index:i}));birdSets.push({model,body,wings,leftWings,individuals});}
 const hideOld=()=>{world.fauna?.forEach(a=>a.visible=false);world.birdBatches?.forEach(b=>{b.visible=false;b.count=0})};hideOld();
 function local(p,r=[0,0,0],s=[1,1,1]){dummy.position.set(...p);dummy.rotation.set(...r);dummy.scale.set(...s);dummy.updateMatrix();localMatrix.copy(dummy.matrix);return localMatrix}
 function partTransform(mesh,index,p,rotation=[0,0,0],s=[1,1,1]){matrix.multiplyMatrices(parentMatrix,local(p,rotation,s));mesh.setMatrixAt(index,matrix)}
 function crossing(a,si,distance,time){if(biome!=='jungle'||!world.natureHazardsEnabled||quality==='Game Only'||a.j!==0||si>1)return null;const tile=world.tiles[a.ti],block=routeBlockFor(tile,distance),phase=((time+block*5.7+si*18)%48+48)%48;if(phase>12||anchorNearJunction(world,tile,a.x,a.z,18))return null;const direction=(block+si)%2===0?1:-1;return {id:`nature-${block}-${si}`,x:direction*(-20+phase/12*40),z:distance-block*160+a.z,localZ:a.z,heading:direction>0?-Math.PI/2:Math.PI/2,trot:true};}
 world.natureHazards=(distance,time,enabled)=>{world.natureHazardsEnabled=!!enabled;if(!enabled||quality==='Game Only'||biome!=='jungle')return [];const hazards=[];groundSets.forEach((set,si)=>{for(const a of set.individuals){const p=crossing(a,si,distance,time);if(!p||Math.abs(p.x)>16||p.z>35||p.z< -200)continue;const c=set.model.config;hazards.push({id:p.id,x:p.x,z:p.z,width:c.length*a.scale*1.23,length:c.width*a.scale*2.0,species:set.model.name});}});return hazards.slice(0,3);};
 function animate(distance,time){renderedHazards=[];if(quality==='Game Only'){root.visible=air.visible=false;root.traverse(m=>{if(m.isInstancedMesh)m.count=0});air.traverse(m=>{if(m.isInstancedMesh)m.count=0});renderedAnimals=renderedBirds=0;visibleSpecies=[];hideOld();return;}root.visible=air.visible=true;const perTile={Low:1,High:2,Ultra:3,'Ultra+':4}[quality]||2,airCount={Low:3,High:8,Ultra:12,'Ultra+':16}[quality]||8;let contacts=0;renderedAnimals=0;renderedBirds=0;visibleSpecies=[];
 for(const [speciesIndex,set] of groundSets.entries()){const {model,parts}=set,c=model.config;let n=0,legs=0;for(const a of set.individuals){if(a.j>=perTile)continue;const tile=world.tiles[a.ti];let block=tile.userData.routeBlock??a.ti-1;while(distance-block*160>320)block+=5;while(distance-block*160< -640)block-=5;const worldZ=distance-block*160+a.z;if(worldZ>55||worldZ< -400||anchorNearJunction(world,tile,a.x,a.z,18))continue;const crossingPose=crossing(a,speciesIndex,distance,time);const amble=c.kind==='seal'?.025:c.kind==='hare'?.055:.13,bob=c.kind==='hare'?Math.max(0,Math.sin(time*.62+a.phase))*.035:Math.sin(time*.78+a.phase)*.008,x=crossingPose?crossingPose.x:a.x+Math.sin(time*.14+a.phase)*amble,z=crossingPose?crossingPose.localZ:a.z+Math.sin(time*.16+a.phase)*amble,y=a.sample(x,z);dummy.position.set(x,y+.015+bob,distance-block*160+z);dummy.rotation.set(0,crossingPose?crossingPose.heading:a.heading+Math.sin(time*.11+a.phase)*.12,0);dummy.scale.setScalar(a.scale);dummy.updateMatrix();parentMatrix.copy(dummy.matrix);partTransform(parts.body,n,[0,0,0]);if(crossingPose)renderedHazards.push({id:crossingPose.id,mesh:parts.body,index:n,x,z:distance-block*160+z});if(parts.fur)partTransform(parts.fur,n,[0,0,0]);partTransform(parts.head,n,model.headPivot,[Math.sin(time*.47+a.phase)*.075+.04,Math.sin(time*.23+a.phase)*.21,0]);if(parts.tail)partTransform(parts.tail,n,model.tailPivot,[Math.sin(time*.6+a.phase)*.08,Math.sin(time*.83+a.phase)*.20,0]);if(parts.leg)for(let k=0;k<4;k++){const front=k<2,side=k%2?-1:1;partTransform(parts.leg,legs++,[side*c.width*.67,c.height-.10,(front?-.33:.34)*c.length],[Math.sin(time*(crossingPose?7:.52)+a.phase+(front?0:2))*(crossingPose?.46:amble*.6),0,side*.025]);}dummy.position.set(x,y+.012,distance-block*160+z);dummy.rotation.set(-Math.PI/2,0,-(crossingPose?crossingPose.heading:a.heading));dummy.scale.set(c.width*3.3*a.scale,c.length*1.6*a.scale,1);dummy.updateMatrix();shadow.setMatrixAt(contacts++,dummy.matrix);n++;}for(const [name,m]of Object.entries(parts)){m.count=name==='leg'?legs:n;m.visible=name!=='fur'||quality==='Ultra'||quality==='Ultra+';m.castShadow=quality!=='Low'&&name!=='fur';m.instanceMatrix.needsUpdate=true;}renderedAnimals+=n;if(n)visibleSpecies.push(model.name);}
 shadow.count=contacts;shadow.instanceMatrix.needsUpdate=true;
 for(const set of birdSets){const c=set.model.config;let n=0;for(const a of set.individuals){if(a.index>=airCount)continue;const phase=time*(c.raptor?.095:.15)+a.phase,glide=c.raptor||c.owl?.65:.30,wingbeat=Math.sin(time*c.flap*Math.PI*2+a.phase)*(Math.sin(time*.17+a.phase)>.25?glide*.28:.57),x=a.x+Math.sin(phase)*12,z=((a.z+distance*.08+time*1.3)%290+290)%290-270;dummy.position.set(x,a.y+Math.sin(phase*.84)*1.25,z);dummy.rotation.set(Math.sin(phase)*.04,Math.cos(phase)*.45,Math.sin(phase)*.055);dummy.scale.setScalar(a.scale);dummy.updateMatrix();parentMatrix.copy(dummy.matrix);partTransform(set.body,n,[0,0,0]);for(let side of[-1,1])partTransform(side===1?set.wings:set.leftWings,n,[side*.071,.012,-.025],[0,0,side*wingbeat]);n++;}for(const m of[set.body,set.wings,set.leftWings]){m.count=n;m.instanceMatrix.needsUpdate=true;m.castShadow=quality!=='Low';}renderedBirds+=n;}
 lastTime=time;hideOld();}
 const oldQuality=world.quality;world.quality=q=>{oldQuality(q);quality=q;hideOld();animate(world.wildlifeDistance||0,lastTime)};
 world.setNatureDifficulty=enabled=>{world.natureHazardsEnabled=!!enabled;animate(world.wildlifeDistance||0,lastTime);};
 const oldUpdate=world.update;world.update=(distance,time,x)=>{oldUpdate(distance,time,x);world.wildlifeDistance=distance;animate(distance,time)};
 const oldDetails=world.details;world.details=()=>({...oldDetails(),wildlife:renderedAnimals,birds:renderedBirds,wildlifeSpecies:[...cat.ground],visibleWildlifeSpecies:[...visibleSpecies],birdSpecies:[...cat.birds],wildlifeArt:{original:true,articulated:true,terrainAnchored:true,groundCount:renderedAnimals,birdCount:renderedBirds,groundCapacity:60,birdCapacity:48,instancedBatches:groundSets.reduce((n,s)=>n+Object.keys(s.parts).length,0)+birdSets.length*3+1,furGeometry:quality==='Ultra'||quality==='Ultra+',featherLayers:true,behaviors:['jungle tapir/capybara crossings when geo effects are enabled','off-road grazing and head turns','small species-dependent body motion','tail movement','species-dependent flapping and gliding'],limits:'Procedural stylized anatomy; no full skeletal locomotion or ecological AI'}});
 world.disposeWildlifeArt=()=>{const geometries=new Set(),materials=new Set(),textures=new Set();for(const group of[root,air]){group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const mat of Array.isArray(o.material)?o.material:o.material?[o.material]:[])materials.add(mat)});group.removeFromParent();}for(const mat of materials){for(const key of['map','bumpMap','alphaMap'])if(mat[key])textures.add(mat[key]);mat.dispose()}textures.forEach(t=>t.dispose());geometries.forEach(g=>g.dispose());};
 world.wildlifeArt={catalog:cat,groundSets,birdSets,root,air,hazardRenderInfo:()=>renderedHazards};animate(0,0);return installWildlifeDetails(world,buildWildlifeModel,buildBirdModel);
}





