import {stochasticSurface9} from './surfaceFinish9.js';
import * as T from 'three';
import {scenerySurface8 as surfaces} from './scenerySurface8.js';
import {blenderScenery8} from './blenderScenery8.js';
import {installUltraScenery} from './ultraScenery8.js';
import {installOcean9} from './ocean9.js';
const rockGeometryCache=new Map();
function groundResponse9(mat,shore,biome){mat.onBeforeCompile=shader=>{shader.vertexShader='varying vec3 groundPosition9;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ngroundPosition9=position;');shader.fragmentShader='varying vec3 groundPosition9;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`#include <map_fragment>
 float sediment9=sin(groundPosition9.x*.61+sin(groundPosition9.z*.29))*sin(groundPosition9.z*.37+groundPosition9.x*.17);
 diffuseColor.rgb*=1.+sediment9*.028;
 ${shore?`float wetShore9=(1.-smoothstep(-43.,-35.,groundPosition9.x+sin(groundPosition9.z*.039)*.24));diffuseColor.rgb*=1.-wetShore9*.30;`:''}
 `);if(shore)shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor=mix(roughnessFactor,.44,(1.-smoothstep(-43.,-35.,groundPosition9.x)));');};mat.customProgramCacheKey=()=>`ground-response-v9-${biome}-${shore}`;}
function sculptedRock(index){const key='weathered-rock-'+index;if(rockGeometryCache.has(key))return rockGeometryCache.get(key);const d=blenderScenery8[key],g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(d.p,3));g.setAttribute('normal',new T.Float32BufferAttribute(d.n,3));g.setAttribute('uv',new T.Float32BufferAttribute(d.uv,2));g.setIndex(d.i);g.computeBoundingSphere();g.userData.artShared=true;rockGeometryCache.set(key,g);return g;}
function ultraWater(w,active){if(!w)return;const m=w.material;if(!m.uniforms.ultraScenery8){m.uniforms.ultraScenery8={value:0};m.fragmentShader='uniform float ultraScenery8;\n'+m.fragmentShader;m.fragmentShader=m.fragmentShader.replace('vec3 surfaceNormal = normalize( noise.xzy * vec3( 1.5, 1.0, 1.5 ) );',`vec3 surfaceNormal = normalize( noise.xzy * vec3( 1.5, 1.0, 1.5 ) );
 vec2 capillary=vec2(sin(worldPosition.x*5.2+worldPosition.z*2.3+time*2.4),cos(worldPosition.x*3.7-worldPosition.z*4.1+time*1.8));
 surfaceNormal=normalize(surfaceNormal+vec3(capillary.x,0.,capillary.y)*.026*ultraScenery8);
 `);m.fragmentShader=m.fragmentShader.replace('vec3 outgoingLight = albedo;',`vec3 outgoingLight = albedo;
 float shoreWash=exp(-abs(worldPosition.x+40.5)*.85)*pow(max(0.,sin(worldPosition.x*1.4+worldPosition.z*.11-time*.65+sin(worldPosition.z*.31)*.4)),16.);
 outgoingLight=mix(outgoingLight,sunColor*.48,shoreWash*.24*ultraScenery8);
 `);m.needsUpdate=true;}m.uniforms.ultraScenery8.value=active?1:0;}
function patchWater(w){if(!w||w.userData.clearWater)return;w.userData.clearWater=true;const m=w.material;m.transparent=true;m.depthWrite=false;m.uniforms.distortionScale.value=1.25;m.fragmentShader=m.fragmentShader.replace('float rf0 = 0.3;','float rf0 = 0.020;').replace('vec3 scatter = max( 0.0, dot( surfaceNormal, eyeDirection ) ) * waterColor;',`float shoreDepth=clamp((-worldPosition.x-40.)*.105+.35,.25,18.);vec3 shallow=vec3(.035,.34,.32),deep=waterColor*.65;vec3 optical=mix(shallow,deep,1.-exp(-shoreDepth*.24));vec3 scatter=max(0.,dot(surfaceNormal,eyeDirection))*optical;`).replace('gl_FragColor = vec4( outgoingLight, alpha );',`float waterAlpha=clamp(.32+reflectance*.6+(1.-exp(-shoreDepth*.32))*.58,.35,.98);gl_FragColor=vec4(outgoingLight,waterAlpha);`);m.needsUpdate=true;}
export function installWorldArt(world,renderer,biome){
 const roadKind={coastline:'road',jungle:'dirtroad',desert:'rockroad',tundra:'iceroad'}[biome],roadTex=surfaces(roadKind),groundTex=surfaces(biome==='tundra'?'snow':biome==='desert'?'sand':'ground'),groundTint={coastline:0x7b776f,tundra:0xbcc9cf,desert:0x9a805f,jungle:0x6f755e}[biome]||0x808080,oldRoad=world.asphalt,road=new T.MeshPhysicalMaterial({color:0x66696a,...roadTex,roughness:biome==='tundra'?.82:1,metalness:0,normalScale:new T.Vector2(biome==='tundra'?.20:biome==='desert'?.65:.36,biome==='tundra'?.20:biome==='desert'?.65:.36),clearcoat:biome==='tundra'?.28:0,clearcoatRoughness:biome==='tundra'?.34:.85,specularIntensity:biome==='tundra'?.65:.30});
 if(biome==='coastline')road.normalScale.set(.55,.55);
 road.onBeforeCompile=shader=>{shader.vertexShader='varying vec2 roadArtPosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nroadArtPosition=vec2(position.x,-position.y);');shader.fragmentShader='varying vec2 roadArtPosition;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`#include <map_fragment>
  float roadLanePhase=fract(roadArtPosition.x*.25)*4.-2.;
  float roadWheelWear=exp(-pow((abs(roadLanePhase)-.77)/.28,2.));
  float roadBroadWear=sin(roadArtPosition.y*.0392699+sin(roadArtPosition.x*.41))*sin(roadArtPosition.y*.1178097)*.023;
  diffuseColor.rgb*=1.-roadWheelWear*.065+roadBroadWear;
 `);};road.customProgramCacheKey=()=> 'original-road-surface-v9';
 const ground=[];world.tiles.forEach(tile=>tile.traverse(m=>{if(!m.isMesh)return;if(m.material===oldRoad)m.material=road;if(m.userData.groundSurface){const shore=biome==='coastline'&&m.geometry.parameters?.width===38,tex=shore?surfaces('sand'):groundTex;const mat=new T.MeshStandardMaterial({color:shore?0x9d8b72:groundTint,...tex,roughness:shore?.88:biome==='tundra'?.8:.98,normalScale:new T.Vector2(shore?.26:.45,shore?.26:.45)});mat.vertexColors=!!m.geometry.getAttribute('color');groundResponse9(mat,shore,biome);m.material=mat;ground.push({mat,tex,kind:shore?'sand':biome==='tundra'?'snow':biome==='desert'?'sand':'ground'})}}));world.asphalt=road;
 const rockTex=surfaces('rock');Object.assign(world.rockMat,rockTex);world.rockMat.bumpMap=null;world.rockMat.normalScale=new T.Vector2(.70,.70);world.rockMat.color.set(0xffffff);world.rockMat.roughness=1;
 const rocks=[];world.tiles.forEach((tile,index)=>tile.traverse(m=>{if(m.isMesh&&m.material===world.rockMat){rocks.push({mesh:m,low:m.geometry,high:sculptedRock(index%3)});m.userData.originalBlenderRock=true;}}));
 let bed;if(biome==='coastline'){const geo=new T.PlaneGeometry(1700,1800,100,90);geo.rotateX(-Math.PI/2);const a=geo.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i)-890,z=a.getZ(i)-520;a.setXYZ(i,x,-Math.min(14,.6+Math.max(0,-x-40)*.11)+Math.sin(x*.27+z*.12)*.04,z)}geo.computeVertexNormals();const mat=new T.MeshStandardMaterial({color:0x82997e,...surfaces('sand'),roughness:.86});bed=new T.Mesh(geo,mat);bed.receiveShadow=true;world.scene.add(bed);}
 const oldQuality=world.quality;world.quality=q=>{oldQuality(q);const plain=q==='Game Only',ultra=q==='Ultra+',activeRoad=ultra?surfaces(roadKind,true):roadTex;if(plain||q==='Low')world.scene.environment=null;world.reflectionDirty=true;road.color.set(plain?0x626d72:0x66696a);road.map=plain?null:activeRoad.map;road.normalMap=(q==='Low'||plain)?null:activeRoad.normalMap;road.roughnessMap=plain?null:activeRoad.roughnessMap;road.needsUpdate=true;rocks.forEach(r=>{r.mesh.geometry=(q==='Low'||plain)?r.low:r.high});Object.assign(world.rockMat,ultra?surfaces('rock',true):rockTex);world.rockMat.needsUpdate=true;ground.forEach(({mat,tex,kind})=>{tex=ultra?surfaces(kind,true):tex;mat.roughnessMap=tex.roughnessMap;mat.map=(q==='Low'||plain)?null:tex.map;mat.normalMap=(q==='Low'||plain)?null:tex.normalMap;mat.needsUpdate=true});patchWater(world.ocean().water);ultraWater(world.ocean().water,ultra)};
 const oldLighting=world.lighting;world.lighting=day=>{oldLighting(day);const night=day==='night';const water=world.ocean().water;if(water){water.material.uniforms.sunDirection.value.copy(world.sun.position).normalize();water.material.uniforms.waterColor.value.set(night?0x092d43:0x146a75);water.material.uniforms.sunColor.value.copy(world.sun.color).multiplyScalar(night?.16:1)}world.reflectionDirty=true;};
 const oldUpdate=world.update;world.update=(distance,time,x)=>{oldUpdate(distance,time,x);if(bed)bed.position.y=world.water.position.y;};
 let cubeTarget,cube,captures=0;world.reflections=player=>{if(!world.reflectionDirty)return;world.reflectionDirty=false;const size=(world.preset==='Low'||world.preset==='Game Only')?0:world.preset==='High'?128:world.preset==='Ultra'?256:384;if(!size){world.scene.environment=null;player.traverse(m=>{if(m.isMesh&&m.material.isMeshPhysicalMaterial){m.material.envMap=null;m.material.needsUpdate=true}});return;}if(!cubeTarget||cubeTarget.width!==size){cubeTarget?.dispose();cubeTarget=new T.WebGLCubeRenderTarget(size,{type:T.HalfFloatType,generateMipmaps:true,minFilter:T.LinearMipmapLinearFilter});cube=new T.CubeCamera(.1,600,cubeTarget)}const changed=[];const hide=o=>{if(o?.visible){changed.push(o);o.visible=false}};hide(player);hide(world.ocean().water);hide(world.ocean().foam);hide(world.wildlifeArtRoot);world.tiles.forEach(t=>{if(Math.abs(t.position.z)>180)hide(t)});cube.position.set(player.position.x,1.8,0);world.scene.environment=null;cube.update(renderer,world.scene);world.scene.environment=cubeTarget.texture;changed.forEach(o=>o.visible=true);player.traverse(m=>{if(m.isMesh&&m.material.isMeshPhysicalMaterial){m.material.envMap=cubeTarget.texture;m.material.envMapIntensity=.72;m.material.needsUpdate=true}});captures++;};
 const oldDetails=world.details;world.details=()=>({...oldDetails(),clearShallows:biome==='coastline',waterOptics:biome==='coastline'?'transparent shallows, depth-color absorption, layered normals and planar reflection':'none',materialDetail:'correlated original aggregate / wear / height-derived normal / roughness; Blender trunks and rocks',roadSurface:({coastline:'asphalt',jungle:'compacted dirt',desert:'rocky aggregate',tundra:'blue ice'}[biome]),localCarReflection:world.preset!=='Low'&&world.preset!=='Game Only',reflectionCaptures:captures});
 world.disposeWorldArt=()=>{cubeTarget?.dispose();const oldRocks=new Set(rocks.map(r=>r.low));oldRocks.forEach(g=>g.dispose());};return installOcean9(installUltraScenery(world,biome),biome);
}



