const fs=require('fs'),path=require('path'),crypto=require('crypto'),folder=__dirname;
const data=JSON.parse(fs.readFileSync(path.join(folder,'data-validation.json'),'utf8')),read=name=>fs.existsSync(path.join(folder,name))?JSON.parse(fs.readFileSync(path.join(folder,name),'utf8')):null,components=read('component-validation.json'),integrated=read('integrated-validation.json');
const files=['treePacks.js','sceneryUnderstory.js','ultraScenery8.js','plantSurface9.js','blenderScenery8.js','blenderUltraScenery8.js'].map(name=>({path:'work/engine-v9/'+name,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.resolve(folder,'../engine-v9',name))).digest('hex')}));fs.writeFileSync(path.join(folder,'source-hashes.json'),JSON.stringify(files,null,2));
const rows=data.geometry.filter(g=>g.lod===3).map(g=>`| ${g.biome} / species ${g.kind+1} | ${g.trianglesBefore.toLocaleString('en-US')} | ${g.trianglesAfter.toLocaleString('en-US')} | ${((1-g.trianglesAfter/g.trianglesBefore)*100).toFixed(1)}% |`).join('\n');
const report=`# V9 original vegetation refinement

This is the scenery component handoff for the v9 working source. V8 source hashes remain unchanged. It does not claim an installed v9 release, measured whole-game frame rate, or photographic authenticity.

## Changes

- Authored tree branches have staggered attachment heights, unequal reach, tapered forks and varied terminal sprays. Palms have unequal frond length and droop. Conifers retain their species and use narrow needle geometry.
- Smaller, irregularly oriented leaves use correlated original color, normal and roughness maps. Leaf colors vary within a restrained species palette. Close leaf surfaces remain curved; grass blades have asymmetric widths, bends and root-to-tip shading.
- Grass clumps have varied heights and gaps. Close grass and litter follow irregular seeded patches instead of evenly spaced rows. Terrain sampling, road setbacks and dynamic intersection clearances remain active.
- Blender 4.5.5 generated 13 offline meshes: ten trunk/root LOD variants were refined and three original rock variants retained. The editable scene is **original-scenery-v9.blend**, generated by **generate-scenery-v9.py**. Curved trunks have continuous exported normals and irregular buttress roots that extend down to the ground. This was actual Blender modeling/export; no downloaded art was used.
- Geometry changes reduce repeated detail: close grass is 220 versus 420 triangles per clump; litter is 160 versus 252. This is explicit authored geometry, with no automatic quality reduction.

## Contracts checked

CPU report **data-validation.json** passed: ${data.models.length} Blender meshes, ${data.geometry.length} generated component combinations, six shared plant texture channels and ${data.cases.length} biome/tier/restoration cases. Position/index/normal data are finite and triangles are nondegenerate at the documented numeric threshold. All ${data.anchors.reduce((n,a)=>n+a.trees,0)} fixture tree anchors and transforms match v8 exactly. Close ground details are sampled onto the current terrain and remain outside the road and intersection setbacks.

Game Only, Low, High, Ultra and Ultra+ remain available. Lazy Ultra+ meshes bind to route/depth materials, hide and set counts to zero when leaving their tier, and restore correctly. Shared immutable geometry/material/texture ownership remains marked with artShared; world-owned instance buffers remain compatible with the existing LRU disposal policy.

## Captures and runtime validation

Matched component renderer: ${components?.passed?'PASS':'PENDING'}; ${components?.rows?.length||0} saved captures, ${components?.errors?.length||0} reported renderer errors. Fixed camera, framing, lighting and tier are held equal within each before/after pair. See **GALLERY.html** and **component-validation.json**. Component bundle SHA256: ${components?.bundleSha256||'pending'}.

Integrated coastline/jungle renderer: ${integrated?.passed?'PASS':'PENDING'}; ${integrated?.rows?.length||0} quality transitions, ${integrated?.captures?.length||0} captures. This exercises current v9 roads, terrain, lighting, route normals, shoreline and shared reflection setup alongside vegetation. It is an isolated renderer fixture, not the final game UI, postprocessing or sustained benchmark. Integrated bundle SHA256: ${integrated?.bundleSha256||'pending'}.

Browser closure: component ${components?.browserClosed??'pending'}; integrated ${integrated?.browserClosed??'pending'}. External requests: component ${components?.external?.length??'pending'}; integrated ${integrated?.external?.length??'pending'}.

## Geometry comparison

These are source component triangle counts, not a performance measurement. Species order is the unchanged order in treePacks.js.

| Ultra+ tree | V8 triangles | V9 triangles | Reduction |
|---|---:|---:|---:|
${rows}

## Packaging inputs and limits

Runtime changes are confined to **work/engine-v9/treePacks.js**, **sceneryUnderstory.js**, **ultraScenery8.js**, **plantSurface9.js** and generated **blenderScenery8.js**. **blenderUltraScenery8.js** is retained unchanged. Source hashes are in **source-hashes.json**. Original assets, generator, test procedures, raw reports and captures are contained in **work/scenery-assets-v9**. No v8 stage, install, audio, physics or car source was changed by this scenery work.

Final full-game matrix, sustained performance and installed-package checks belong to the parent release pass. The vegetation remains procedural and stylized in some silhouettes; finer detail does not establish photographic equivalence. Visual acceptance notes are recorded separately in **VISUAL-REVIEW.md** after capture inspection.
`;
fs.writeFileSync(path.join(folder,'SCENERY-V9.md'),report);
const ids=[...new Set(components?.rows?.map(r=>r.id)||[])];const gallery=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Original vegetation · V8 / V9</title><style>body{margin:0;background:#15212a;color:#e7efef;font:16px/1.55 system-ui}main{max-width:1480px;margin:auto;padding:38px 24px}h1{font-size:36px;margin:0}p{max-width:850px;color:#bfcdcf}section{margin:34px 0}h2{text-transform:capitalize;font-size:22px}article{display:grid;grid-template-columns:1fr 1fr;gap:14px}figure{margin:0}img{width:100%;display:block;border-radius:7px}figcaption{padding:7px 0;color:#aebfc4}@media(max-width:700px){article{grid-template-columns:1fr}}</style><main><h1>Original vegetation</h1><p>Matched V8 / V9 component captures using the same camera, light and detail tier. These isolate authored shape and surface changes; they are not photographs or full-game performance results.</p>${ids.map(id=>`<section><h2>${id.replaceAll('-',' ')}</h2><article><figure><img src="${id}-before.png" alt="V8 ${id}"><figcaption>V8 reference</figcaption></figure><figure><img src="${id}-after.png" alt="V9 ${id}"><figcaption>V9 candidate</figcaption></figure></article></section>`).join('')}<section><h2>Scene integration</h2><p>Current v9 terrain, lighting and shoreline alongside the vegetation. These frames use the renderer fixture; final game verification is reported separately.</p><article>${(integrated?.captures||[]).map(file=>`<figure><img src="${file}" alt="${file.replaceAll('-',' ')}"><figcaption>${file.replace('.png','').replaceAll('-',' ')}</figcaption></figure>`).join('')}</article></section></main></html>`;fs.writeFileSync(path.join(folder,'GALLERY.html'),gallery);console.log('Scenery report and offline gallery written.');
